-- Tạo database

CREATE DATABASE IF NOT EXISTS ApartmentManagement CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ApartmentManagement;

--  ACCOUNT
CREATE TABLE IF NOT EXISTS ACCOUNT (
    username VARCHAR(50) PRIMARY KEY,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20)
);

-- BUILDING_MANAGER
CREATE TABLE IF NOT EXISTS BUILDING_MANAGER (
    managerID INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    phoneNumber VARCHAR(15),
    username VARCHAR(50),
    CONSTRAINT FK_BuildingManager_User FOREIGN KEY (username) REFERENCES ACCOUNT(username)
);

-- ACCOUNTANT
CREATE TABLE IF NOT EXISTS ACCOUNTANT (
    accountantID INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50),
    CONSTRAINT FK_Accountant_User FOREIGN KEY (username) REFERENCES ACCOUNT(username)
);

-- BUILDING
CREATE TABLE IF NOT EXISTS BUILDING (
    buildingID VARCHAR(10) PRIMARY KEY,
    managerID INT,
    address VARCHAR(200),
    numApartment INT,
    FOREIGN KEY (managerID) REFERENCES BUILDING_MANAGER(managerID)
);

-- APARTMENT
CREATE TABLE IF NOT EXISTS APARTMENT (
    apartmentID VARCHAR(10) PRIMARY KEY,
    buildingID VARCHAR(10),
    numResident INT DEFAULT 0,
    FOREIGN KEY (buildingID) REFERENCES BUILDING(buildingID)
);

-- RESIDENT
CREATE TABLE IF NOT EXISTS RESIDENT (
    residentID INT AUTO_INCREMENT PRIMARY KEY,
    apartmentID VARCHAR(10),
    fullName VARCHAR(100) NOT NULL,
    age INT,
    date DATE,
    phoneNumber VARCHAR(15),
    isOwner TINYINT(1) DEFAULT 0,
    username VARCHAR(50),
    FOREIGN KEY (apartmentID) REFERENCES APARTMENT(apartmentID),
    CONSTRAINT FK_Resident_User FOREIGN KEY (username) REFERENCES ACCOUNT(username)
);

-- BILL
CREATE TABLE IF NOT EXISTS BILL (
    billID INT AUTO_INCREMENT PRIMARY KEY,
    apartmentID VARCHAR(10),
    accountantID INT,
    createDate DATETIME DEFAULT CURRENT_TIMESTAMP(),
    deadline DATE,
    typeOfBill VARCHAR(50),
    amount DECIMAL(18, 0),
    total DECIMAL(18, 0),
    status VARCHAR(20),
    paymentMethod VARCHAR(50),
    FOREIGN KEY (apartmentID) REFERENCES APARTMENT(apartmentID),
    FOREIGN KEY (accountantID) REFERENCES ACCOUNTANT(accountantID)
);

-- SERVICE_FEE
CREATE TABLE IF NOT EXISTS SERVICE_FEE (
    serviceID INT AUTO_INCREMENT PRIMARY KEY,
    serviceName VARCHAR(100),
    unitPrice DECIMAL(18, 0),
    buildingID VARCHAR(10),
    FOREIGN KEY (buildingID) REFERENCES BUILDING(buildingID)
);


-- PAYMENT_TRANSACTION

CREATE TABLE IF NOT EXISTS PAYMENT_TRANSACTION (
    transID INT AUTO_INCREMENT PRIMARY KEY,
    residentID INT NOT NULL,
    amount DECIMAL(18, 0) NOT NULL,
    paymentContent VARCHAR(50),
    paymentMethod VARCHAR(20),
    status ENUM('Pending','Success','Failed','Expired') DEFAULT 'Pending',
    createdDate DATETIME DEFAULT CURRENT_TIMESTAMP(),
    payDate DATETIME NULL,
    gatewayTransCode VARCHAR(100) NULL,
    FOREIGN KEY (residentID) REFERENCES RESIDENT(residentID)
);

-- TRANSACTION_DETAIL
CREATE TABLE IF NOT EXISTS TRANSACTION_DETAIL (
    detailID INT AUTO_INCREMENT PRIMARY KEY,
    transID INT NOT NULL,
    billID INT NOT NULL,
    amount DECIMAL(18, 0),
    FOREIGN KEY (transID) REFERENCES PAYMENT_TRANSACTION(transID),
    FOREIGN KEY (billID) REFERENCES BILL(billID)
);

-- =============================
-- INDEX
-- =============================

-- Tối ưu join/lookup theo các khóa ngoại
CREATE INDEX IDX_BUILDING_MANAGERID ON BUILDING(managerID);
CREATE INDEX IDX_APARTMENT_BUILDINGID ON APARTMENT(buildingID);
CREATE INDEX IDX_RESIDENT_APARTMENTID ON RESIDENT(apartmentID);
CREATE INDEX IDX_BILL_APARTMENTID ON BILL(apartmentID);
CREATE INDEX IDX_BILL_ACCOUNTANTID ON BILL(accountantID);
CREATE INDEX IDX_SERVICEFEE_BUILDINGID ON SERVICE_FEE(buildingID);
CREATE INDEX IDX_PAYMENTTX_RESIDENTID ON PAYMENT_TRANSACTION(residentID);
CREATE INDEX IDX_TXDETAIL_TRANSID ON TRANSACTION_DETAIL(transID);
CREATE INDEX IDX_TXDETAIL_BILLID ON TRANSACTION_DETAIL(billID);

-- Tối ưu lọc theo trạng thái/thời gian (các màn hình thường lọc theo status, deadline, ngày tạo)
CREATE INDEX IDX_BILL_STATUS ON BILL(status);
CREATE INDEX IDX_BILL_DEADLINE ON BILL(deadline);
CREATE INDEX IDX_BILL_CREATEDATE ON BILL(createDate);
CREATE INDEX IDX_PAYMENTTX_STATUS ON PAYMENT_TRANSACTION(status);
CREATE INDEX IDX_PAYMENTTX_CREATEDDATE ON PAYMENT_TRANSACTION(createdDate);

-- Tối ưu tra cứu theo username
CREATE INDEX IDX_BUILDINGMANAGER_USERNAME ON BUILDING_MANAGER(username);
CREATE INDEX IDX_ACCOUNTANT_USERNAME ON ACCOUNTANT(username);
CREATE INDEX IDX_RESIDENT_USERNAME ON RESIDENT(username);

-- Đảm bảo: 1 username chỉ gắn tối đa 1 bản ghi vai trò
CREATE UNIQUE INDEX UQ_BUILDING_MANAGER_USERNAME ON BUILDING_MANAGER(username);
CREATE UNIQUE INDEX UQ_ACCOUNTANT_USERNAME ON ACCOUNTANT(username);
CREATE UNIQUE INDEX UQ_RESIDENT_USERNAME ON RESIDENT(username);


-- Tránh lặp cùng 1 bill trong cùng 1 giao dịch
CREATE UNIQUE INDEX UQ_TXDETAIL_TRANS_BILL ON TRANSACTION_DETAIL(transID, billID);
